;//////////////////////////////////////////////////////////////////////////////
;FILE: ChallengeMode.ini  //////////////////////////////////////////////////
;//////////////////////////////////////////////////////////////////////////////
;
; This file contains setup data for the Generals' Challenge Mode setup and load screens.
; Steve Copeland 6/23/03
;
; A general must exist for 0 through NUM_GENERALS, as defined in ChallengeGenerals.cpp.
; These are mapped to buttons representing geographical locations (see ChallengeMode.wnd).
;

ChallengeGenerals

  GeneralPersona0
    PlayerTemplate = FactionAmericaAirForceGeneral
    StartsEnabled = yes
    BioNameString = GUI:BioNameEntry_Pos0
    BioDOBString = GUI:BioDOBEntry_Pos0
    BioBirthplaceString = GUI:BioBirthplaceEntry_Pos0
    BioStrategyString = GUI:BioStrategyEntry_Pos0
    BioRankString = GUI:BioRankEntry_Pos0
    BioBranchString = GUI:BioBranchEntry_Pos0
    BioClassNumberString = GUI:BioClassNumber_Pos0
    BioPortraitSmall = PAAirGen_S
    BioPortraitLarge = PAAirGen
    PortraitMovieLeftName = PortraitAirGenLeft
    PortraitMovieRightName = PortraitAirGenRight
    DefeatedImage = PAAirGen_L
    VictoriousImage = PAAirGen_W
    DefeatedString = GUI:BioDefeatedEntry_Pos0
    VictoriousString = GUI:BioVictoriousEntry_Pos0
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer07
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound =Taunts_Grainger064
    LossSound =Taunts_Grainger065
    NameSound = none
    Campaign = CHALLENGE_0
  END

  GeneralPersona1
    PlayerTemplate = FactionGLAToxinGeneral
    StartsEnabled = yes
    BioNameString = GUI:BioNameEntry_Pos1
    BioDOBString = GUI:BioDOBEntry_Pos1
    BioBirthplaceString = GUI:BioBirthplaceEntry_Pos1
    BioStrategyString = GUI:BioStrategyEntry_Pos1
    BioRankString = GUI:BioRankEntry_Pos1
    BioBranchString = GUI:BioBranchEntry_Pos1
    BioClassNumberString = GUI:BioClassNumber_Pos1
    BioPortraitSmall = PUThraxGen_S
    BioPortraitLarge = PUThraxGen
    PortraitMovieLeftName = PortraitDrThraxLeft
    PortraitMovieRightName = PortraitDrThraxRight
    DefeatedImage = PUThraxGen_L
    VictoriousImage = PUThraxGen_W
    DefeatedString = GUI:BioDefeatedEntry_Pos1
    VictoriousString = GUI:BioVictoriousEntry_Pos1
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer09
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound =Taunts_Toxin100
    LossSound =Taunts_Toxin101
    NameSound = none
    Campaign = CHALLENGE_1
  END

  GeneralPersona2
    PlayerTemplate = FactionChinaNukeGeneral
    StartsEnabled = yes
    BioNameString = GUI:BioNameEntry_Pos2
    BioDOBString = GUI:BioDOBEntry_Pos2
    BioBirthplaceString = GUI:BioBirthplaceEntry_Pos2
    BioStrategyString = GUI:BioStrategyEntry_Pos2
    BioRankString = GUI:BioRankEntry_Pos2
    BioBranchString = GUI:BioBranchEntry_Pos2
    BioClassNumberString = GUI:BioClassNumber_Pos2
    BioPortraitSmall = PNNukeGen_S
    BioPortraitLarge = PNNukeGen
    PortraitMovieLeftName = PortraitNukeGenLeft
    PortraitMovieRightName = PortraitNukeGenRight
    DefeatedImage = PNNukeGen_L
    VictoriousImage = PNNukeGen_W
    DefeatedString = GUI:BioDefeatedEntry_Pos2
    VictoriousString = GUI:BioVictoriousEntry_Pos2
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer06
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound =Taunts_Nuke062
    LossSound =Taunts_Nuke063
    NameSound = none
    Campaign = CHALLENGE_2
  END

  GeneralPersona3
    PlayerTemplate = FactionAmericaSuperWeaponGeneral
    StartsEnabled = yes
    BioNameString = GUI:BioNameEntry_Pos3
    BioDOBString = GUI:BioDOBEntry_Pos3
    BioBirthplaceString = GUI:BioBirthplaceEntry_Pos3
    BioStrategyString = GUI:BioStrategyEntry_Pos3
    BioRankString = GUI:BioRankEntry_Pos3
    BioBranchString = GUI:BioBranchEntry_Pos3
    BioClassNumberString = GUI:BioClassNumber_Pos3
    BioPortraitSmall = PASuperwpnGen_S
    BioPortraitLarge = PASuperwpnGen
    PortraitMovieLeftName = PortraitSuperGenLeft
    PortraitMovieRightName = PortraitSuperGenRight
    DefeatedImage = PASuperwpnGen_L
    VictoriousImage = PASuperwpnGen_W
    DefeatedString = GUI:BioDefeatedEntry_Pos3
    VictoriousString = GUI:BioVictoriousEntry_Pos3
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer08
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound =Taunts_Turtle100
    LossSound =Taunts_Turtle101
    NameSound = none
    Campaign = CHALLENGE_3
  END

  GeneralPersona4
    PlayerTemplate = FactionChinaTankGeneral
    StartsEnabled = yes
    BioNameString = GUI:BioNameEntry_Pos4
    BioDOBString = GUI:BioDOBEntry_Pos4
    BioBirthplaceString = GUI:BioBirthplaceEntry_Pos4
    BioStrategyString = GUI:BioStrategyEntry_Pos4
    BioRankString = GUI:BioRankEntry_Pos4
    BioBranchString = GUI:BioBranchEntry_Pos4
    BioClassNumberString = GUI:BioClassNumber_Pos4
    BioPortraitSmall = PNTankGen_S
    BioPortraitLarge = PNTankGen
    PortraitMovieLeftName = PortraitTankGenLeft
    PortraitMovieRightName = PortraitTankGenRight
    DefeatedImage = PNTankGen_L
    VictoriousImage = PNTankGen_W
    DefeatedString = GUI:BioDefeatedEntry_Pos4
    VictoriousString = GUI:BioVictoriousEntry_Pos4
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer04
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound =Taunts_Tank096
    LossSound =Taunts_Tank097
    NameSound = none
    Campaign = CHALLENGE_4
  END

  GeneralPersona5
    PlayerTemplate = FactionAmericaLaserGeneral
    StartsEnabled = yes
    BioNameString = GUI:BioNameEntry_Pos5
    BioDOBString = GUI:BioDOBEntry_Pos5
    BioBirthplaceString = GUI:BioBirthplaceEntry_Pos5
    BioStrategyString = GUI:BioStrategyEntry_Pos5
    BioRankString = GUI:BioRankEntry_Pos5
    BioBranchString = GUI:BioBranchEntry_Pos5
    BioClassNumberString = GUI:BioClassNumber_Pos5
    BioPortraitSmall = PALaserGen_S
    BioPortraitLarge = PALaserGen
    PortraitMovieLeftName = PortraitLaserGenLeft
    PortraitMovieRightName = PortraitLaserGenRight
    DefeatedImage = PALaserGen_L
    VictoriousImage = PALaserGen_W
    DefeatedString = GUI:BioDefeatedEntry_Pos5
    VictoriousString = GUI:BioVictoriousEntry_Pos5
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer10
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound =Taunts_Laser095
    LossSound =Taunts_Laser096
    NameSound = none
    Campaign = CHALLENGE_5
  END

  GeneralPersona6
    PlayerTemplate = FactionGLAStealthGeneral
    StartsEnabled = yes
    BioNameString = GUI:BioNameEntry_Pos6
    BioDOBString = GUI:BioDOBEntry_Pos6
    BioBirthplaceString = GUI:BioBirthplaceEntry_Pos6
    BioStrategyString = GUI:BioStrategyEntry_Pos6
    BioRankString = GUI:BioRankEntry_Pos6
    BioBranchString = GUI:BioBranchEntry_Pos6
    BioClassNumberString = GUI:BioClassNumber_Pos6
    BioPortraitSmall = PUStealth_S
    BioPortraitLarge = PUStealth
    PortraitMovieLeftName = PortraitStealthGenLeft
    PortraitMovieRightName = PortraitStealthGenRight
    DefeatedImage = PUStealth_L
    VictoriousImage = PUStealth_W
    DefeatedString = GUI:BioDefeatedEntry_Pos6
    VictoriousString = GUI:BioVictoriousEntry_Pos6
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer03
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound =Taunts_Stealth100
    LossSound =Taunts_Stealth101
    NameSound = none
    Campaign = CHALLENGE_6
  END

  GeneralPersona7
    PlayerTemplate = FactionChinaInfantryGeneral
    StartsEnabled = yes
    BioNameString = GUI:BioNameEntry_Pos7
    BioDOBString = GUI:BioDOBEntry_Pos7
    BioBirthplaceString = GUI:BioBirthplaceEntry_Pos7
    BioStrategyString = GUI:BioStrategyEntry_Pos7
    BioRankString = GUI:BioRankEntry_Pos7
    BioBranchString = GUI:BioBranchEntry_Pos7
    BioClassNumberString = GUI:BioClassNumber_Pos7
    BioPortraitSmall = PNInfantryGen_S
    BioPortraitLarge = PNInfantryGen
    PortraitMovieLeftName = PortraitInfantryGenLeft
    PortraitMovieRightName = PortraitInfantryGenRight
    DefeatedImage = PNInfantryGen_L
    VictoriousImage = PNInfantryGen_W
    DefeatedString = GUI:BioDefeatedEntry_Pos7
    VictoriousString = GUI:BioVictoriousEntry_Pos7
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer05
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound = Taunts_Infantry095
    LossSound = Taunts_Infantry096
    NameSound = none
    Campaign = CHALLENGE_7
  END

  GeneralPersona8
    PlayerTemplate = FactionGLADemolitionGeneral
    StartsEnabled = Yes
    BioNameString = GUI:BioNameEntry_Pos8
    BioDOBString = GUI:BioDOBEntry_Pos8
    BioBirthplaceString = GUI:BioBirthplaceEntry_Pos8
    BioStrategyString = GUI:BioStrategyEntry_Pos8
    BioRankString = GUI:BioRankEntry_Pos8
    BioBranchString = GUI:BioBranchEntry_Pos8
    BioClassNumberString = GUI:BioClassNumber_Pos8
    BioPortraitSmall = PUDemolGen_S
    BioPortraitLarge = PUDemolGen
    PortraitMovieLeftName = PortraitDemolitionGenLeft
    PortraitMovieRightName = PortraitDemolitionGenRight
    DefeatedImage = PUDemolGen_L
    VictoriousImage = PUDemolGen_W
    DefeatedString = GUI:BioDefeatedEntry_Pos8
    VictoriousString = GUI:BioVictoriousEntry_Pos8
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer02
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound = Taunts_Demo093
    LossSound = Taunts_Demo094
    NameSound = none
    Campaign = CHALLENGE_8
  END

  GeneralPersona9
    PlayerTemplate = FactionAmerica ;;CyberneticGeneral (+USABoss)
    StartsEnabled = Yes
    BioNameString = GUI:BioNameEntry_PosA
    BioDOBString = GUI:BioDOBEntry_PosA
    BioBirthplaceString = GUI:BioBirthplaceEntry_PosA
    BioStrategyString = GUI:BioStrategyEntry_PosA
    BioRankString = GUI:BioRankEntry_PosA
    BioBranchString = GUI:BioBranchEntry_PosA
    BioClassNumberString = GUI:BioClassNumber_PosA
    BioPortraitSmall = PUCybrGen_S
    BioPortraitLarge = PUCybrGen
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer10c
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    PortraitMovieLeftName = PortraitCyberGenLeft
    PortraitMovieRightName = PortraitCyberGenRight
    DefeatedImage = PUCybrGen
    VictoriousImage = PUCybrGen
    DefeatedString = GUI:BioDefeatedEntry_PosA
    VictoriousString = GUI:BioVictoriousEntry_PosA
    WinSound = Taunts_Cyber030
    LossSound = Taunts_Cyber029
    NameSound = none
    Campaign = CHALLENGE_9
  END

  GeneralPersona10
    PlayerTemplate = FactionChina ;;FlameGeneral (+ChinaBoss)
    StartsEnabled = Yes
    BioNameString = GUI:BioNameEntry_PosB
    BioDOBString = GUI:BioDOBEntry_PosB
    BioBirthplaceString = GUI:BioBirthplaceEntry_PosB
    BioStrategyString = GUI:BioStrategyEntry_PosB
    BioRankString = GUI:BioRankEntry_PosB
    BioBranchString = GUI:BioBranchEntry_PosB
    BioClassNumberString = GUI:BioClassNumber_PosB
    BioPortraitSmall = PUFlameGen_S
    BioPortraitLarge = PUFlameGen
    PortraitMovieLeftName = PortraitFlameGenLeft
    PortraitMovieRightName = PortraitFlameGenRight
    DefeatedImage = PUFlameGen
    VictoriousImage = PUFlameGen
    DefeatedString = GUI:BioDefeatedEntry_PosB
    VictoriousString = GUI:BioVictoriousEntry_posB
    SelectionSound = none
    PreviewSound = Taunts_GCAnnouncer10b
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound = Taunts_Flame009
    LossSound = Taunts_Flame008
    NameSound = none
    Campaign = CHALLENGE_10
  END

  GeneralPersona11
    PlayerTemplate = FactionGLA ;;AssaultGeneral (+GLABoss)
    StartsEnabled = Yes
    BioNameString = GUI:BioNameEntry_PosC
    BioDOBString = GUI:BioDOBEntry_PosC
    BioBirthplaceString = GUI:BioBirthplaceEntry_PosC
    BioStrategyString = GUI:BioStrategyEntry_PosC
    BioRankString = GUI:BioRankEntry_PosC
    BioBranchString = GUI:BioBranchEntry_PosC
    BioClassNumberString = GUI:BioClassNumber_PosC
    BioPortraitSmall = PUAsltGen_S
    BioPortraitLarge = PUAsltGen
    PortraitMovieLeftName = PortraitAssaultGenLeft
    PortraitMovieRightName = PortraitAssaultGenRight
    DefeatedImage = PUAsltGen
    VictoriousImage = PUAsltGen
    DefeatedString = GUI:BioDefeatedEntry_Pos11
    VictoriousString = GUI:BioVictoriousEntry_Pos11
    PreviewSound = Taunts_GCAnnouncer10a
    SelectionSound = none
    TauntSound1 = none
    TauntSound2 = none
    TauntSound3 = none
    WinSound = Taunts_GLABoss097
    LossSound = Taunts_GLABoss098
    NameSound = none
    Campaign = CHALLENGE_11
  END

END
