;//////////////////////////////////////////////////////////////////////////////
;FILE: Credits.ini   //////////////////////////////////////////////////////////
;//////////////////////////////////////////////////////////////////////////////
; Credits Format:
; The Credits.ini file is easy to use, at first glance though, it looks messed up.
; Here's a brief tutorial on the steps needed to enter the credits.
;--------------------------------------------------------------------------------
; The credits work by first declaring the style "Style =" you want for the text that will
; follow until another style is declared.  Then you can enter any number of "Text =" lines
; that will be using that style. Finally, you can have any number of "Blank" lines you want,
; anywhere in the file.
;
; -------------
; STYLES:
; Styles can be one of four types:
;     "TITLE"
;     "MINORTITLE"
;     "NORMAL"
;     "COLUMN"
; "TITLE" is the largest font, so every text line after that will be large.
; "MINORTITLE" is smaller the TITLE but should be used for important things other then Big Titles :)
; "NORMAL" is the smallest font, and should be used for the normal texts like names.
; "COLUMN" uses the same font as Normal but now requres that ever two "Text =" lines below it, will be on
;          one line in the screen.  Look at the example below to more visually understand this.
; You declare a style with a line like this and they can be declared in any order:
; Style = TITLE
;
; --------------
; TEXT:
; Text lines are the lines that will contain the text that will actually be displayed.  This line can
; contain either quoted strings, String Labels, or <BLANK>.
;
; Quoted strings are anything within double quotes ("Blah").  These should only be used for strings that
; are not going to be translated (so things like names).
; Example: Text = "Chris Huybregts"
;
; String labels are strings that we look up in the string file for.  How the code knows it's a string label
; is by searching for a ':' in the label.  This should be used for titles, positions, whatever. Remember that
; if you add a label here, it needs to also live in the Generals.str file
; Example: Text = GUI:Programmer
;
; <BLANK> is used if we want to have a no text in a text field.  This is useful for columns in which you don't
; want something in one or the other columns.
; Example: Text = <BLANK>
;
; ---------------
; BLANK:
; Blank is used whenever we want a blank line to separate text. Just put this identifier, with nothing else following it.
; Example: Blank
;
; ----------------
; EXAMPLE:
; Here's an example of each of the things.
;
; Credits
;   "This is where the header goes"
;   Style = TITLE
;   Text = GUI:EAPacificTitle
;   Blank
;   Style = NORMAL
;   Text = GUI:LegalStuff
;   Blank
;   Blank
;   Style = MINORTITLE
;   Text = GUI:Programmers
;   Style = COLUMN
;   Text = GUI:SeniorProgrammers
;   Text = "John Doe"
;   Text = <BLANK>
;   Text = "Jane Doe"
; END
; The output of the above would look like:
;               EA Pacific //In big letters
;
;               Trademark  // in a smaller text
;
;
;              Programmers // in the middle size font
;  Senior Programmers     John Doe  // the columns
;                         Jane Doe  // an example of using <BLANK>

Credits
; BEGIN HEADER
  ScrollRate              = 2                   ;How many pixels to move
  ScrollRateEveryFrames   = 1                   ;How many frames inbetween that we do the ScrollRate
  ScrollDown            = NO                    ;We can scroll up, or down... don't ask my why we'd want to scroll down
  TitleColor            = R:255 G:210 B:100 A:255 ;Color for style type TITLE
  MinorTitleColor       = R:255 G:210 B:100 A:255 ;Color for style type MINORTITLE
  NormalColor           = R:255 G:255 B:200 A:255 ;Color for style type NORMAL ;R:255 G:190 B:0 A:255
; END HEADER

  Style = TITLE
  Text = "Contra"
  Text = CREDITS:MOD01
  Text = CREDITS:MOD01V
  Style = NORMAL
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:MOD02
  Blank
  Style = NORMAL
  Text = CREDITS:AUTHOR
  Text = "pestryakov@rambler.ru"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:MOD03
  Blank
  Style = NORMAL
  Text = "Andrey [Creator] Pestryakov"
  Text = "Davor [dce] Cesarec"
  Text = "Antonio [Predator_BG] Panayotov"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:MOD04
  Blank
  Style = NORMAL
  Text = "Andrey [Creator] Pestryakov"
  Text = "Davor [dce] Cesarec"
  Text = "triatomic"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:FX
  Blank
  Style = NORMAL
  Text = "Antonio [Predator_BG] Panayotov"
  Text = "SagittariusA"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:MOD07
  Blank
  Style = NORMAL
  Text = "Andrey [Creator] Pestryakov"
  Text = "Antonio [Predator_BG] Panayotov"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:MOD09
  Blank
  Style = NORMAL
  Text = "Andrey [Creator] Pestryakov"
  Text = "Antonio [Predator_BG] Panayotov"
  Text = "Marakar"
  Text = "Adriane[Deathscythe]"
  Text = "WWB2"
  Text = "Jundiyy"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:TESTERS
  Blank
  Style = NORMAL
  Text = "GG `PeRSuN^"
  Text = "Jundiyy"
  Text = "Marakar"
  Text = "Adriane[Deathscythe]"
  Text = "WWB2"
  Text = "triatomic"
  Text = "Baltika9"
  Text = "Core Daff"
  Text = "Magnum"
  Text = "Dromed"
  Text = "Ui_Shigure"
  Text = "kun"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:COLLABORATORS
  Blank
  Style = NORMAL
  Text = "Adriane[Deathscythe]"
  Text = "triatomic"
  Text = "WWB2"
  Text = "SagittariusA"
  Text = "Ui_Shigure"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:VOICEACTORS
  Blank
  Style = NORMAL
  Text = "Gundamwen"
  Text = "Maelstrom"
  Text = "Matthew Vanston"
  Text = "George Exley"
  Text = "Greekas"
  Text = "Forrest McGilvray"
  Text = "TryToEpic"
  Text = "Connor Miranda"
  Text = "Cari Scholtens"
  Text = "Caroline Sawatzki"
  Text = "Kinsmarck"
  Text = "KMart"
  Text = "zanet"
  Text = "Haubibban"
  Text = "Tracer Krieg"
  Text = "Drake Warlord"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:MUSIC
  Blank
  Style = NORMAL
  Text = "Charlie Lockwood"
  Text = "ToneSlave"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:LAUNCHER
  Blank
  Style = NORMAL
  Text = "Antonio [Predator_BG] Panayotov"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:PR
  Blank
  Style = NORMAL
  Text = "Jundiyy"
  Text = "Marakar"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:MODLocalEng
  Blank
  Style = NORMAL
  Text = "Andrey [Creator] Pestryakov"
  Text = "Antonio [Predator_BG] Panayotov"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:MODLocalRus
  Blank
  Style = NORMAL
  Text = "Andrey [Creator] Pestryakov"
  Text = "Antonio [Predator_BG] Panayotov"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:TAKENFROM
  Blank
  Style = NORMAL
  Text = "Dawn of War. Dark Crusade"
  Text = "Total Annihilation"
  Text = "HOMMV"
  Text = "Men of War. Condemned Heroes"
  Text = "Command & Conquer 3. Tiberium Wars"
  Text = "Command & Conquer 3. Kane's Wrath"
  Text = "Command & Conquer. Red Alert 3"
  Blank
  Blank
  Style = TITLE
  Text = CREDITS:SPECIAL_THANKS_TO_SUPPORTERS
  Blank
  Style = NORMAL
  Text = "Michael Sterr"
  Text = "Ignatev Evgeniy Olegovich"
  Text = "Stefan Vorwerk"
  Text = "PhantomDesigns"
  Text = "Muhammad Naeem Yasin"
  Text = "Rico Kaden"
  Text = "Stav Sameach"
  Text = "James Davis"
  Text = "Yan Sun Bin"
  Text = "Matthew Aldridge"
  Text = "Lutz Becker"
  Text = "Jeramy Nusco"
  Text = "Matus Hochstein"
  Text = "Andrey Novak"
  Text = "Erich Haeusser"
  Text = "Farhad Samadov"
  Text = "Thomas Schmelzle"
  Text = "Erik Jewdokimow"
  Text = "ALEX IT-Solutions"
  Text = "Dennis Bradley"
  Text = "Simon Sol"
  Text = "Adrian Burger"
  Text = "Leo Berrehouc"
  Text = "Patrick Grimm"
  Text = "Aleksandr Konoplyan"
  Text = "richard violet"
  Text = "Nils Hansen"
  Text = "Abd Al Hade Asayed"
  Text = "Ki Tae Kim"
  Text = "Alasdair Darrant"
  Text = "Nicklas Christiansen"
  Text = "Juggarin Houngmangkala"
  Text = "Raul Lopez"
  Text = "irakli barbakadze"
  Text = "Wadah hamza"
  Text = "Pierre Van uden"
  Text = "Werner Alsemgeest"
  Text = "Joshua Walters"
  Text = "Daesung Oh"
  Text = "Marcel Dohr"
  Text = "yo hola"
End