
;------------------------------------------------------------------------------
Object AmericaBuildingDefenseGun

  ; *** ART Parameters ***
  SelectPortrait         = SABuildingDefense
  ButtonImage            = SABuildingDefense

  ;------------ Security turret ------------------
  Draw = W3DModelDraw ModuleTag_Draw0X
    OkToChangeModelColor = Yes

    DefaultConditionState
      Model = ABDefense
      Turret = TurretUp01
      TurretPitch = TurretEL
      WeaponFireFXBone = PRIMARY MuzzleUp
      WeaponMuzzleFlash = PRIMARY MuzzleFXUp
      WeaponLaunchBone = PRIMARY MuzzleUp
      WeaponFireFXBone = SECONDARY WeaponB
      WeaponLaunchBone = SECONDARY WeaponB
      WeaponFireFXBone = TERTIARY WeaponB
      WeaponLaunchBone = TERTIARY WeaponB
    End
  End

  ; ***DESIGN parameters ***
  DisplayName         = UPGRADE:BuildingDefense
  Side                = America
  EditorSorting       = STRUCTURE

  WeaponSet
    Conditions        = None
    Weapon           = PRIMARY    BuildingSecurityGun
    Weapon           = SECONDARY  BuildingSecurityMissileWeapon
    Weapon           = TERTIARY   StingerDroneMissileWeaponAir
    PreferredAgainst = TERTIARY   AIRCRAFT
    ShareWeaponReloadTime = Yes
  End

  ArmorSet
    Conditions = None
    Armor      = BaseDefenseArmor
    DamageFX   = StructureDamageFXNoShake
  End

  BuildCost           = 750
  BuildTime           = 15
  VisionRange         = 175
  ShroudClearingRange = 175
  CommandSet = StopOnlyGenericCommandSet

  ExperienceValue     = 29 29 29 29
  IsTrainable         = No

  ; *** AUDIO Parameters ***
  VoiceSelect         = NoSound
  VoiceMove           = NoSound
  VoiceAttack         = NoSound
  SoundMoveStart      = NoSound
  UnitSpecificSounds
    TurretMoveStart   = NoSound
    TurretMoveLoop    = TurretMoveLoop
  End

  ; *** ENGINEERING Parameters ***
  RadarPriority = NOT_ON_RADAR
  KindOf        = PRELOAD VEHICLE DRONE SELECTABLE CAN_ATTACK ATTACK_NEEDS_LINE_OF_SIGHT SCORE

  Body = ActiveBody ModuleTag_03
    MaxHealth       = 300.0
    InitialHealth   = 300.0
    SubdualDamageCap = 600
    SubdualDamageHealRate = 500
    SubdualDamageHealAmount = 50
  End

  Behavior = AIUpdateInterface ModuleTag_AI
    Turret
      TurretTurnRate = 180
      TurretPitchRate = 180
      FiresWhileTurning = Yes
      AllowsPitch       = Yes
      MinPhysicalPitch  = -90
      RecenterTime = 5000
      ControlledWeaponSlots = PRIMARY SECONDARY TERTIARY
      MinIdleScanInterval = 250    ; in milliseconds
      MaxIdleScanInterval = 250    ; in milliseconds
      MinIdleScanAngle    = 0      ; in degrees off the natural turret angle
      MaxIdleScanAngle    = 360    ; in degrees off the natural turret angle
    End
    AutoAcquireEnemiesWhenIdle = Yes
    MoodAttackCheckRate        = 200
  End

  Locomotor = SET_NORMAL BuildingSecurityLocomotor

  Behavior = PhysicsBehavior ModuleTag_05
    Mass = 5000.0
    KillWhenRestingOnGround = Yes
    AllowBouncing = No
    PitchRollYawFactor = 0
  End

  Behavior = SlavedUpdate ModuleTag_04
  End

  Behavior = DestroyDie ModuleTag_08
    DeathTypes = ALL
  End

  Behavior = TransitionDamageFX ModuleTag_10
    ReallyDamagedParticleSystem1 = Bone:Smoke RandomBone:Yes PSys:SmokeSmallContinuous01
    ReallyDamagedFXList1 = Loc: X:0 Y:0 Z:0 FXList:FX_BattleDroneDamageTransitionSmall
  End

  Behavior   = CreateObjectDie ModuleTag_13
    CreationList = OCL_TinyStructureDebris
  End

  Behavior   = FXListDie ModuleTag_14
    DeathFX      = FX_GenericTankDeathExplosion
  End

  Behavior = UpgradeDie  ModuleTag_12
    DeathTypes = ALL
    UpgradeToRemove = Upgrade_USABuildingDefense
  End

  Behavior = AutoHealBehavior ModuleTag_SelfHealing
    HealingAmount = 10
    HealingDelay = 833
    StartHealingDelay = 5000
    StartsActive = Yes
  End

  Behavior = FlammableUpdate ModuleTag_21
    AflameDuration = 5000
    AflameDamageAmount = 3
    AflameDamageDelay = 500
  End

  Geometry = CYLINDER
  GeometryMajorRadius = 5
  GeometryMinorRadius = 5
  GeometryHeight = 40.0
  GeometryIsSmall = Yes
;  Shadow = SHADOW_VOLUME
;  ShadowSizeX = 89
End

;------------------------------------------------------------------------------
Object AmericaBuildingDefenseLaser

  ; *** ART Parameters ***
  SelectPortrait         = SABuildingDefense
  ButtonImage            = SABuildingDefense

  ;------------ Security turret ------------------
  Draw = W3DModelDraw ModuleTag_Draw0X
    OkToChangeModelColor = Yes
    ExtraPublicBone = LaserSpot01

    DefaultConditionState
      Model = ABDefenseL
      Turret = TurretUp01
    End
  End

  ; ***DESIGN parameters ***
  DisplayName         = UPGRADE:BuildingDefense
  Side                = America
  EditorSorting       = STRUCTURE

  WeaponSet
    Conditions        = None
    Weapon      = PRIMARY AvengerPointDefenseLaserOne
    Weapon      = SECONDARY BuildingAntiInfantryLaser
  End

  ArmorSet
    Conditions = None
    Armor      = BaseDefenseArmor
    DamageFX   = StructureDamageFXNoShake
  End

  BuildCost           = 750
  BuildTime           = 15
  VisionRange         = 175
  ShroudClearingRange = 175
  CommandSet = StopOnlyGenericCommandSet

  ExperienceValue     = 29 29 29 29
  IsTrainable         = No

  ; *** AUDIO Parameters ***
  VoiceSelect         = NoSound
  VoiceMove           = NoSound
  VoiceAttack         = NoSound
  SoundMoveStart      = NoSound
  UnitSpecificSounds
    TurretMoveStart   = NoSound
    TurretMoveLoop    = TurretMoveLoop
  End

  ; *** ENGINEERING Parameters ***
  RadarPriority = NOT_ON_RADAR
  KindOf        = PRELOAD VEHICLE DRONE SELECTABLE CAN_ATTACK ATTACK_NEEDS_LINE_OF_SIGHT SCORE

  Body = StructureBody ModuleTag_03
    MaxHealth       = 300.0
    InitialHealth   = 300.0
    SubdualDamageCap = 600
    SubdualDamageHealRate = 500
    SubdualDamageHealAmount = 50
  End

  Behavior = AIUpdateInterface ModuleTag_AI
    Turret
      TurretTurnRate = 180
      RecenterTime = 5000
      ControlledWeaponSlots = PRIMARY SECONDARY TERTIARY
      MinIdleScanInterval   = 250    ; in milliseconds
      MaxIdleScanInterval   = 250    ; in milliseconds
      MinIdleScanAngle      = 0      ; in degrees off the natural turret angle
      MaxIdleScanAngle      = 360    ; in degrees off the natural turret angle
    End
    AutoAcquireEnemiesWhenIdle = Yes
    MoodAttackCheckRate        = 250
  End

  Locomotor = SET_NORMAL BuildingSecurityLocomotor

  Behavior = PhysicsBehavior ModuleTag_05
    Mass = 5000.0
    KillWhenRestingOnGround = Yes
    AllowBouncing = No
    PitchRollYawFactor = 0
  End

  Behavior = SlavedUpdate ModuleTag_04
  End

  Behavior = DestroyDie ModuleTag_08
    DeathTypes = ALL
  End

  Behavior = TransitionDamageFX ModuleTag_10
    ReallyDamagedParticleSystem1 = Bone:Smoke RandomBone:Yes PSys:SmokeSmallContinuous01
    ReallyDamagedFXList1 = Loc: X:0 Y:0 Z:0 FXList:FX_BattleDroneDamageTransitionSmall
  End

  Behavior = CreateObjectDie ModuleTag_13
    CreationList = OCL_TinyStructureDebris
  End

  Behavior = FXListDie ModuleTag_14
    DeathFX = FX_GenericTankDeathExplosion
  End

  Behavior = UpgradeDie  ModuleTag_12
    DeathTypes = ALL
    UpgradeToRemove = Upgrade_USABuildingDefense
  End

  Behavior = BaseRegenerateUpdate ModuleTag_BR
  End

  Behavior = AutoHealBehavior ModuleTag_SelfHealing
    HealingAmount = 10
    HealingDelay = 833
    StartHealingDelay = 5000
    StartsActive = Yes
  End

  Behavior = FlammableUpdate ModuleTag_21
    AflameDuration = 5000
    AflameDamageAmount = 3
    AflameDamageDelay = 500
  End

  Geometry = CYLINDER
  GeometryMajorRadius = 5
  GeometryMinorRadius = 5
  GeometryHeight = 40.0
  GeometryIsSmall = Yes
;  Shadow = SHADOW_VOLUME
;  ShadowSizeX = 89
End

;------------------------------------------------------------------------------
Object AmericaBuildingDefenseGunHigh

  ; *** ART Parameters ***
  SelectPortrait         = SABuildingDefense
  ButtonImage            = SABuildingDefense

  ;------------ Security turret ------------------
  Draw = W3DModelDraw ModuleTag_Draw0X
    OkToChangeModelColor = Yes

    DefaultConditionState
      Model = ABDefenseH
      Turret = TurretUp01
      TurretPitch = TurretEL
      WeaponFireFXBone = PRIMARY MuzzleUp
      WeaponMuzzleFlash = PRIMARY MuzzleFXUp
      WeaponLaunchBone = PRIMARY MuzzleUp
      WeaponFireFXBone = SECONDARY WeaponB
      WeaponLaunchBone = SECONDARY WeaponB
      WeaponFireFXBone = TERTIARY WeaponB
      WeaponLaunchBone = TERTIARY WeaponB
    End
  End

  ; ***DESIGN parameters ***
  DisplayName        = UPGRADE:BuildingDefense
  Side               = America
  EditorSorting      = STRUCTURE

  WeaponSet
    Conditions       = None
    Weapon           = PRIMARY    BuildingSecurityGun
    Weapon           = SECONDARY  BuildingSecurityMissileWeapon
    Weapon           = TERTIARY   StingerDroneMissileWeaponAir
    PreferredAgainst = PRIMARY    INFANTRY
    PreferredAgainst = SECONDARY  VEHICLE STRUCTURE
    PreferredAgainst = TERTIARY   AIRCRAFT
    ShareWeaponReloadTime = Yes
  End

  ArmorSet
    Conditions = None
    Armor      = BaseDefenseArmor
    DamageFX   = StructureDamageFXNoShake
  End

  BuildCost           = 750
  BuildTime           = 15
  VisionRange         = 175
  ShroudClearingRange = 175
  CommandSet = StopOnlyGenericCommandSet

  ExperienceValue     = 29 29 29 29
  IsTrainable         = No

  ; *** AUDIO Parameters ***
  VoiceSelect         = NoSound
  VoiceMove           = NoSound
  VoiceAttack         = NoSound
  SoundMoveStart      = NoSound
  UnitSpecificSounds
    TurretMoveStart   = NoSound
    TurretMoveLoop    = TurretMoveLoop
  End

  ; *** ENGINEERING Parameters ***
  RadarPriority = NOT_ON_RADAR
  KindOf        = PRELOAD VEHICLE DRONE SELECTABLE CAN_ATTACK ATTACK_NEEDS_LINE_OF_SIGHT SCORE

  Body = StructureBody ModuleTag_03
    MaxHealth       = 300.0
    InitialHealth   = 300.0
    SubdualDamageCap = 600
    SubdualDamageHealRate = 500
    SubdualDamageHealAmount = 50
  End

  Behavior = AIUpdateInterface ModuleTag_AI
    Turret
      TurretTurnRate = 180
      TurretPitchRate = 180
      FiresWhileTurning = Yes
      AllowsPitch       = Yes
      MinPhysicalPitch  = -90
      RecenterTime = 5000
      ControlledWeaponSlots = PRIMARY SECONDARY TERTIARY
      MinIdleScanInterval   = 250    ; in milliseconds
      MaxIdleScanInterval   = 250    ; in milliseconds
      MinIdleScanAngle      = 0      ; in degrees off the natural turret angle
      MaxIdleScanAngle      = 360    ; in degrees off the natural turret angle
    End
    AutoAcquireEnemiesWhenIdle = Yes
    MoodAttackCheckRate        = 250
  End

  Locomotor = SET_NORMAL BuildingSecurityLocomotor

  Behavior = PhysicsBehavior ModuleTag_05
    Mass = 5000.0
    KillWhenRestingOnGround = Yes
    AllowBouncing = No
    PitchRollYawFactor = 0
  End

  Behavior = SlavedUpdate ModuleTag_04
  End

  Behavior = DestroyDie ModuleTag_08
    DeathTypes = ALL
  End

  Behavior = TransitionDamageFX ModuleTag_10
    ReallyDamagedParticleSystem1 = Bone:Smoke RandomBone:Yes PSys:SmokeSmallContinuous01
    ReallyDamagedFXList1 = Loc: X:0 Y:0 Z:0 FXList:FX_BattleDroneDamageTransitionSmall
  End

  Behavior   = CreateObjectDie ModuleTag_13
    CreationList = OCL_TinyStructureDebris
  End

  Behavior   = FXListDie ModuleTag_14
    DeathFX      = FX_GenericTankDeathExplosion
  End

  Behavior = BaseRegenerateUpdate ModuleTag_BR
  End

  Behavior = UpgradeDie  ModuleTag_12
    DeathTypes = ALL
    UpgradeToRemove = Upgrade_USABuildingDefense
  End

  Behavior = AutoHealBehavior ModuleTag_SelfHealing
    HealingAmount = 10
    HealingDelay = 833
    StartHealingDelay = 5000
    StartsActive = Yes
  End

  Behavior = FlammableUpdate ModuleTag_21
    AflameDuration = 5000
    AflameDamageAmount = 3
    AflameDamageDelay = 500
  End

  Geometry = CYLINDER
  GeometryMajorRadius = 5
  GeometryMinorRadius = 5
  GeometryHeight = 70.0
  GeometryIsSmall = Yes
;  Shadow = SHADOW_VOLUME
;  ShadowSizeX = 89
End

;------------------------------------------------------------------------------
Object AmericaVehicleMinigunDrone

  ; *** ART Parameters ***
  SelectPortrait       = SAMGD_L
  ButtonImage          = SAMGD

  Draw = W3DModelDraw ModuleTag_01
    OkToChangeModelColor = Yes

    DefaultConditionState
      Model = AVMGDrone
      Turret = Turret
      TurretPitch = TurretEL
      WeaponFireFXBone = PRIMARY FIREPOINT
      WeaponLaunchBone = PRIMARY FIREPOINT
    End

    ConditionState = REALLYDAMAGED
      Model = AVMGDrone_D
    End
  End

  ; ***DESIGN parameters ***
  DisplayName         = OBJECT:MinigunDrone
  Side                = America
  EditorSorting       = VEHICLE
  TransportSlotCount  = 0

  WeaponSet
    Conditions        = None
    Weapon            = PRIMARY MinigunDroneMachineGun
  End

  ArmorSet
    Conditions        = None
    Armor             = DroneArmor
    DamageFX          = SmallTankDamageFX
  End
  ArmorSet
    Conditions        = PLAYER_UPGRADE
    Armor             = DroneArmorCybrUpgraded
    DamageFX          = SmallTankDamageFX
  End

  Behavior = ArmorUpgrade ModuleTag_Armor02
    TriggeredBy = Upgrade_AmericaTransmitionCodes
  End

  BuildCost           = 350
  BuildTime           = 10.0
  VisionRange         = 150
  ShroudClearingRange = 150

  ExperienceValue     = 0 0 0 0
  ExperienceRequired  = 0 20000 50000 60000
  IsTrainable         = Yes

  ; *** AUDIO Parameters ***
  VoiceSelect         = NoSound
  VoiceMove           = NoSound
  VoiceAttack         = NoSound
  SoundMoveStart      = NoSound
  SoundStealthOn  = USStealthOn
  SoundStealthOff = USStealthOff
  UnitSpecificSounds
    TurretMoveStart   = NoSound
    TurretMoveLoop    = TurretMoveLoop
  End

  ; *** ENGINEERING Parameters ***
  RadarPriority       = UNIT
  KindOf = PRELOAD CAN_CAST_REFLECTIONS VEHICLE CAN_ATTACK DRONE NO_SELECT

  Body = ActiveBody ModuleTag_03
    MaxHealth       = 200.0
    InitialHealth   = 200.0
    SubdualDamageCap = 200
    SubdualDamageHealRate = 500
    SubdualDamageHealAmount = 50
  End

  Behavior = AIUpdateInterface ModuleTag_04
    Turret
      TurretTurnRate        = 720
      TurretPitchRate       = 720
      MinPhysicalPitch      = -90
      AllowsPitch           = Yes
      ControlledWeaponSlots = PRIMARY
      FiresWhileTurning   = Yes
    End
    AutoAcquireEnemiesWhenIdle = Yes Stealthed
    MoodAttackCheckRate = 100
  End

  Locomotor = SET_NORMAL BattleDroneLocomotor

  Behavior = PhysicsBehavior ModuleTag_05
    Mass = 50.0
    KillWhenRestingOnGround = Yes
    AllowBouncing = No
  End

  Behavior = MaxHealthUpgrade ModuleTag_06
    TriggeredBy   = Upgrade_AmericaDroneArmor
    AddMaxHealth  = 60.0
    ChangeType    = ADD_CURRENT_HEALTH_TOO   ;Choices are PRESERVE_RATIO, ADD_CURRENT_HEALTH_TOO, and SAME_CURRENTHEALTH
  End

  Behavior = SlavedUpdate ModuleTag_07
    GuardMaxRange = 35      ;How far away from master I'm allowed when master is idle (doesn't wander)
    GuardWanderRange = 35   ;How far away I'm allowed to wander from master while guarding.
    AttackRange = 75        ;How far away from master I'm allowed when master is attacking a target.
    AttackWanderRange = 75  ;How far I'm allowed to wander from target.
    ScoutRange = 75         ;How far away from master I'm allowed when master is moving.
    ScoutWanderRange = 25   ;How far I'm allowed to wander from scout point.
    StayOnSameLayerAsMaster = Yes
  End

  Behavior = DestroyDie ModuleTag_08
    DeathTypes = ALL
  End
  Behavior       = CreateObjectDie  ModuleTag_09
    DeathTypes   = ALL
    CreationList = OCL_AmericaMGDroneExplode
  End

  Behavior                 = TransitionDamageFX ModuleTag_10
    ReallyDamagedParticleSystem1 = Bone:Smoke RandomBone:Yes PSys:SmokeSmallContinuous01
    ReallyDamagedFXList1 = Loc: X:0 Y:0 Z:0 FXList:FX_BattleDroneDamageTransitionSmall
  End

  Behavior     = FXListDie ModuleTag_11
    DeathTypes = ALL
    DeathFX    = FX_AmericaBattleDroneExplode
  End

  Behavior = UpgradeDie  ModuleTag_12
    DeathTypes = ALL
    UpgradeToRemove  = Upgrade_AmericaMinigunDrone
  End

  Behavior = FlammableUpdate ModuleTag_21
    AflameDuration = 5000
    AflameDamageAmount = 3
    AflameDamageDelay = 500
  End

  Behavior = VeterancyGainCreate ModuleTag_Veteran
    StartingLevel = ELITE
    ScienceRequired = SCIENCE_AdvancedAI
  End

  Geometry = CYLINDER
  GeometryMajorRadius = 5
  GeometryMinorRadius = 5
  GeometryHeight = 10.0
  GeometryIsSmall = Yes
  Shadow = SHADOW_VOLUME
  ShadowSizeX = 89
End