;------------------------------------------------------------------------------
;In-Game UI
;
;------------------------------------------------------------------------------

InGameUI
  MaxSelectionSize               = 0 ; <1 to disable
  MessageColor1                  = R:255 G:255 B:255
  MessageColor2                  = R:180 G:180 B:255
  MessagePosition                = X:10 Y:10
  MessageFont                    = Arial
  MessagePointSize               = 10
  MessageBold                    = Yes
  MessageDelayMS                 = 75000

  MilitaryCaptionColor           = R:255 G:255 B:255 A:255
  MilitaryCaptionPosition        = X:10 Y:340

  MilitaryCaptionTitleFont       = Courier New
  MilitaryCaptionTitlePointSize  = 12
  MilitaryCaptionTitleBold       = Yes

  MilitaryCaptionFont            = Courier New
  MilitaryCaptionPointSize       = 12
  MilitaryCaptionBold            = No

  MilitaryCaptionRandomizeTyping = Yes
  ;MilitaryCaptionSpeed           = 1 // not used here anymore
;  MilitaryCaptionDelayMS         = 750 ; Moved to Language.ini so localization can change for their longer strings

  SuperweaponCountdownPosition        = X:0.90 Y:0.01
  SuperweaponCountdownFlashDuration   = 500 ; in milliseconds, 0 to disable
  SuperweaponCountdownFlashColor      = R:255 G:255 B:255

  SuperweaponCountdownNormalFont      = Arial
  SuperweaponCountdownNormalPointSize = 10
  SuperweaponCountdownNormalBold      = No

  SuperweaponCountdownReadyFont       = Arial
  SuperweaponCountdownReadyPointSize  = 10
  SuperweaponCountdownReadyBold       = Yes


  NamedTimerCountdownPosition         = X:0.90 Y:0.666
  NamedTimerCountdownFlashDuration    = 500 ; in milliseconds, 0 to disable
  NamedTimerCountdownFlashColor       = R:255 G:255 B:255

  NamedTimerCountdownNormalFont       = Arial
  NamedTimerCountdownNormalPointSize  = 10
  NamedTimerCountdownNormalBold       = No
  NamedTimerCountdownNormalColor      = R:255 G:255 B:255

  NamedTimerCountdownReadyFont        = Arial
  NamedTimerCountdownReadyPointSize   = 10
  NamedTimerCountdownReadyBold        = No
  NamedTimerCountdownReadyColor       = R:255 G:255 B:255

  FloatingTextTimeOut                 = 333
  FloatingTextMoveUpSpeed             = 30
  FloatingTextVanishRate              = 3

  DrawRMBScrollAnchor                 = No
  MoveRMBScrollAnchor                 = Yes
  PopupMessageColor                   = R:255 G:255 B:255 A:255

  ;SPYDRONE
  SpyDroneRadiusCursor
    Texture       = SccSpyDrone_USA
    Style         = SHADOW_ALPHA_DECAL
    OpacityMin    = 50%
    OpacityMax    = 100%
    OpacityThrobTime = 1000
    Color         = R:240 G:240 B:240 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;ATTACK_SCATTER_AREA
  AttackScatterAreaRadiusCursor
    Texture       = SCCNanoSwarm
    Style         = SHADOW_ALPHA_DECAL
    OpacityMin        = 55%
    OpacityMax        = 75%
    OpacityThrobTime  = 500
    Color             = R:255 G:0 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;SUPERWEAPON_SCATTER_AREA
  SuperweaponScatterAreaRadiusCursor
    Texture           = sccecmbomb
    Style             = SHADOW_ALPHA_DECAL
    OpacityMin        = 25%
    OpacityMax        = 50%
    OpacityThrobTime  = 500
    Color             = R:100 G:210 B:100 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;ATTACK_DAMAGE_AREA
  AttackDamageAreaRadiusCursor
    Texture       = SCCIllusion
    Style         = SHADOW_ALPHA_DECAL
    OpacityMin    = 50%
    OpacityMax    = 100%
    OpacityThrobTime = 1000
    Color         = R:40 G:110 B:210 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;ATTACK_CONTINUE_AREA
  AttackContinueAreaRadiusCursor
    Texture       = SCCEMPPulse_China
    Style         = SHADOW_ALPHA_DECAL
    OpacityMin    = 50%
    OpacityMax    = 100%
    OpacityThrobTime = 1000
    Color         = R:40 G:110 B:210 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;GUARD_AREA
  GuardAreaRadiusCursor
    Texture        = SCCGuard_Generic
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:240 G:240 B:240 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;EMERGENCY_REPAIR
  EmergencyRepairRadiusCursor
    Texture        = SCCRepair
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:240 G:240 B:240 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;FRENZY
  FrenzyRadiusCursor
    Texture        = SCCFrenzy
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:255 G:0 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;FRIENDLY_SPECIALPOWER
  FriendlySpecialPowerRadiusCursor
    Texture        = SCCLeaflet
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:100 G:255 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;OFFENSIVE_SPECIALPOWER
  OffensiveSpecialPowerRadiusCursor
    Texture        = SCCFuelAirBomb_USA
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:255 G:255 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;PARTICLECANNON
  ParticleCannonRadiusCursor
    Texture        = SCCParticleCanon_USA
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:40 G:110 B:210 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;A10STRIKE
  A10StrikeRadiusCursor
    Texture        = SCCA10Strike_USA
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:255 G:156 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;CARPETBOMB
  CarpetBombRadiusCursor
    Texture        = SCCCarpBomb
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:255 G:0 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;DAISYCUTTER
  DaisyCutterRadiusCursor
    Texture        = SCCBomber
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:255 G:0 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;PARADROP
  ParadropRadiusCursor
    Texture        = SCCParadrop_USA
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:227 G:229 B:22 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;SPYSATELLITE
  SpySatelliteRadiusCursor
    Texture        = SCCSpySatellite_USA
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:240 G:240 B:240 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;SPECTREGUNSHIP
  SpectreGunshipRadiusCursor
    Texture       = SCCICBM
    Style         = SHADOW_ALPHA_DECAL
    OpacityMin    = 50%
    OpacityMax    = 100%
    OpacityThrobTime = 1000
    Color            = R:255 G:0 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;HELIX_NAPALM_BOMB
  HelixNapalmBombRadiusCursor
    Texture        = SCCDemolish
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin        = 55%
    OpacityMax        = 75%
    OpacityThrobTime  = 500
    Color             = R:255 G:0 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;NUCLEARMISSILE
  NuclearMissileRadiusCursor
    Texture        = SCCNuclearMissile_China
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:255 G:0 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;EMPPULSE
  EMPPulseRadiusCursor
    Texture        = sccweatherstorm_usa
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:40 G:110 B:210 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;ARTILLERYBARRAGE
  ArtilleryRadiusCursor
    Texture        = SCCArtilleryBarrage_China
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:255 G:156 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;NAPALMSTRIKE
  NapalmStrikeRadiusCursor
    Texture        = SCCNapalmStrike_China
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:255 G:156 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;CLUSTERMINES
  ClusterMinesRadiusCursor
    Texture        = SCCClusterMines_China
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:255 G:156 B:0 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;SCUDSTORM
  ScudStormRadiusCursor
    Texture        = SCCScudStorm_GLA
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:33 G:255 B:67 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;ANTHRAXBOMB
  AnthraxBombRadiusCursor
    Texture        = SCCAnthraxBomb_GLA
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:33 G:255 B:67 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;AMBUSH
  AmbushRadiusCursor
    Texture        = SCCAmbush_GLA
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:227 G:229 B:22 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;RADAR
  RadarRadiusCursor
    Texture        = SCCRadar_GLA
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:240 G:240 B:240 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;CLEARMINES
  ClearMinesRadiusCursor
    Texture        = SCCClear
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:240 G:240 B:240 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

  ;AMBULANCE
  AmbulanceRadiusCursor
    Texture        = SCCAmbulance
    Style          = SHADOW_ALPHA_DECAL
    OpacityMin     = 50%
    OpacityMax     = 100%
    OpacityThrobTime  = 1000
    Color          = R:240 G:240 B:240 A:255
    OnlyVisibleToOwningPlayer = Yes
  End

End
