; FILE: Video.ini /////////////////////////////////////////////////////////////
; This INI file holds all our video tracks
; /////////////////////////////////////////////////////////////////////////////
Video Sizzle
  Filename = Contra_Intro ;NONE ;sizzle_review
  Comment = This is the EA logo screen
End

Video Sizzle640
  Filename = Contra_Intro ;NONE ;sizzle_review640
  Comment = This is the EA logo screen
End


Video EALogoMovie
  Filename = NONE; EA_LOGO
  Comment = This is the EA logo screen
End

Video EALogoMovie640
  Filename = NONE; EA_LOGO640
  Comment = This is the EA logo screen
End

Video GeneralsChallengeBackground
  Filename = VS_small
  Comment = Plays in the background for GC loads
End

Video VSSmall
;  Filename = VS_small
;  Comment = "VS" logo, in flames
End

Video PortraitDrThraxLeft
;  Filename = Comp_ThraxGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitDrThraxRight
;  Filename = Comp_ThraxGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitAirGenLeft
;  Filename = Comp_AirGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitAirGenRight
;  Filename = Comp_AirGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitBossGenLeft
;  Filename = Comp_BossGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitBossGenRight
;  Filename = Comp_BossGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitDemolitionGenLeft
;  Filename = Comp_DemolGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitDemolitionGenRight
;  Filename = Comp_DemolGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitInfantryGenLeft
;  Filename = Comp_InfantryGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitInfantryGenRight
;  Filename = Comp_InfantryGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitLaserGenLeft
;  Filename = Comp_LaserGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitLaserGenRight
;  Filename = Comp_LaserGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitNukeGenLeft
;  Filename = Comp_NukeGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitNukeGenRight
;  Filename = Comp_NukeGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitTankGenLeft
;  Filename = Comp_TankGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitTankGenRight
;  Filename = Comp_TankGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitSuperGenLeft
;  Filename = Comp_SuperGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitSuperGenRight
;  Filename = Comp_SuperGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitStealthGenLeft
;  Filename = Comp_StealthGen_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitStealthGenRight
;  Filename = Comp_StealthGen_inv_000
;  Comment = portrait transition for Generals Challenge load screen
End

Video MD_China01
  Filename = MD_China01_0
  Comment = campaign transition movie
End

Video MD_China02
  Filename = MD_China02_0
  Comment = campaign transition movie
End

Video MD_China03
  Filename = MD_China03_0
  Comment = campaign transition movie
End

Video MD_China04
  Filename = MD_China04_0
  Comment = campaign transition movie
End

Video MD_China05
  Filename = MD_China05_0
  Comment = campaign transition movie
End


Video MD_GLA01
  Filename = MD_GLA01_0
  Comment = campaign transition movie
End

Video MD_GLA02
  Filename = MD_GLA02_0
  Comment = campaign transition movie
End

Video MD_GLA03
  Filename = MD_GLA03_0
  Comment = campaign transition movie
End

Video MD_GLA04
  Filename = MD_GLA04_0
  Comment = campaign transition movie
End

Video MD_GLA05
  Filename = MD_GLA05_0
  Comment = campaign transition movie
End

Video MD_USA01
  Filename = MD_USA01_0
  Comment = campaign transition movie
End

Video MD_USA02
  Filename = MD_USA02_0
  Comment = campaign transition movie
End

Video MD_USA03
  Filename = MD_USA03_0
  Comment = campaign transition movie
End

Video MD_USA04
  Filename = MD_USA04_0
  Comment = campaign transition movie
End

Video MD_USA05
  Filename = MD_USA05_0
  Comment = campaign transition movie
End

Video PortraitCyberneticGenLeft
;  Filename = NONE
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitCyberneticGenRight
;  Filename = NONE
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitAssaultGenLeft
;  Filename = NONE
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitAssaultGenRight
;  Filename = NONE
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitFlameGenLeft
;  Filename = NONE
;  Comment = portrait transition for Generals Challenge load screen
End

Video PortraitFlameGenRight
;  Filename = NONE
;  Comment = portrait transition for Generals Challenge load screen
End

Video test1
  Filename = test1
End