;//////////////////////////////////////////////////////////////////////////////
;FILE: Water.ini (System)
;//////////////////////////////////////////////////////////////////////////////

WaterSet MORNING
  SkyTexture = water_texture_2.tga ;TSCloudWis.tga
  WaterTexture = twwater01.tga
  Vertex00Color = R:200 G:200 B:200
  Vertex10Color = R:200 G:200 B:200
  Vertex01Color = R:200 G:200 B:200
  Vertex11Color = R:200 G:200 B:200
  DiffuseColor   = R:175 G:175 B:175 A:255
  TransparentDiffuseColor = R:150 G:150 B:150 A:128
  UScrollPerMS = 0.01
  VScrollPerMS = -0.01
  SkyTexelsPerUnit = 0.8
  WaterRepeatCount = 26
End

WaterSet AFTERNOON
  SkyTexture = water_texture_2.tga  ;TSCloudWis.tga
  WaterTexture = twwater01.tga
  Vertex00Color = R:225 G:225 B:225
  Vertex10Color = R:225 G:225 B:225
  Vertex01Color = R:225 G:225 B:225
  Vertex11Color = R:225 G:225 B:225
  DiffuseColor   = R:185 G:185 B:185 A:255
  TransparentDiffuseColor = R:255 G:255 B:255 A:128
  UScrollPerMS = 0.01
  VScrollPerMS = -0.01
  SkyTexelsPerUnit = 0.8
  WaterRepeatCount = 26
End

WaterSet EVENING
  SkyTexture = TSCloudSun.tga
  WaterTexture = twwater01.tga
  Vertex00Color = R:150 G:150 B:150
  Vertex10Color = R:150 G:150 B:150
  Vertex01Color = R:150 G:150 B:150
  Vertex11Color = R:150 G:150 B:150
  DiffuseColor   = R:225 G:225 B:225 A:255
  TransparentDiffuseColor = R:150 G:150 B:150 A:96
  UScrollPerMS = 0.01
  VScrollPerMS = -0.01
  SkyTexelsPerUnit = 0.8
  WaterRepeatCount = 26
End

WaterSet NIGHT
  SkyTexture = TSStarFeld.tga
  WaterTexture = twwater01.tga
  Vertex00Color = R:255 G:255 B:255 A:255
  Vertex10Color = R:255 G:255 B:255 A:255
  Vertex01Color = R:255 G:255 B:255 A:255
  Vertex11Color = R:255 G:255 B:255 A:255
  DiffuseColor   = R:100 G:100 B:100 A:255
  TransparentDiffuseColor = R:255 G:255 B:255 A:128
  UScrollPerMS = 0.01
  VScrollPerMS = -0.01
  SkyTexelsPerUnit = 1.6
  WaterRepeatCount = 26
End

; WaterTransparency can be overridden per each map to change these values.
WaterTransparency
  TransparentWaterMinOpacity = 0.75        ;opacity of water at maximum depth - 1.0 is opaque, 0 transparent.
  TransparentWaterDepth = 2.5              ;depth below water surface at which it becomes opaque (unless clipped by TransparentWaterMinOpacity)
;  StandingWaterColor = R:200 G:200 B:200   ;material color used to tint the water surface.
;  StandingWaterColor = R:200 G:200 B:180   ;material color used to tint the water surface.
  StandingWaterColor = R:200 G:200 B:160   ;material color used to tint the water surface.
  StandingWaterTexture = twwater01.tga     ;main texture used for water (usually something blue that looks like water).
;  AdditiveBlending = Yes                   ;use additive blending instead of alpha blending?
  RadarWaterColor = R:140 G:140 B:255      ;color of water on radar display.
End